export type Locale = 'vi' | 'en'

export const proposalContent = {
  vi: {
    nav: { home: 'duc@proposal:~' },
    hero: {
      cmd: '$ cat proposal.md',
      title1: 'Đề xuất hợp tác',
      title2: 'Fullstack Developer',
      subtitle:
        'Năng lực, phạm vi công việc, và lộ trình đóng góp 90 ngày đầu — mọi thứ quý công ty cần trước khi trao đổi trực tiếp. Đọc trong ~4 phút.',
      fields: {
        name: 'họ tên',
        nameValue: 'Lưu Minh Đức',
        role: 'vai trò',
        roleValue: 'Fullstack Developer',
        experience: 'kinh nghiệm',
        experienceValue: 'BSS Commerce · FPT Software',
        to: 'gửi tới',
        toDefault: 'Phòng Nhân sự',
      },
      ctaContact: 'liên hệ →',
      ctaCv: '↓ cv.pdf',
    },
    s1: {
      num: '01',
      cmd: '$ whoami --verbose',
      title: 'Giới thiệu & năng lực',
      name: 'Lưu Minh Đức',
      tagline: 'Fullstack Developer · MERN & Next.js · FPT University (SE, 2021–2025)',
      bio1: 'Tôi xây dựng sản phẩm từ đầu đến cuối — từ thiết kế database, API cho đến từng pixel người dùng thao tác. Kinh nghiệm thực chiến gồm phát triển Shopify app tại BSS Commerce, chương trình Intern → Fresher React tại FPT Software, và vai trò trưởng nhóm 2 dự án full-stack đưa từ số 0 lên production.',
      bio2: 'Tôi coi trọng code sạch, dễ bảo trì, và học công nghệ mới nhanh — sẵn sàng nhận trách nhiệm end-to-end thay vì chỉ một mảnh nhỏ của hệ thống.',
      traits: ['Tư duy giải quyết vấn đề', 'Học nhanh', 'Kinh nghiệm lead nhóm', 'Ship end-to-end'],
      skillGroups: [
        { key: 'languages', tags: ['JavaScript', 'TypeScript', 'Java'] },
        { key: 'frameworks', tags: ['React', 'Next.js', 'NestJS', 'Redux Toolkit', 'TanStack Query'] },
        { key: 'database', tags: ['MongoDB', 'MySQL', 'SQL Server', 'PostgreSQL', 'GraphQL'] },
        { key: 'other', tags: ['Socket.io', 'Firebase', 'Docker', 'Shopify APIs'] },
      ],
    },
    s2: {
      num: '03',
      cmd: '$ cat context.md',
      title: 'Bối cảnh & nhu cầu',
      intro: 'Một đội sản phẩm hiệu quả cần developer có thể nhận một yêu cầu và đưa nó đến production — không dừng lại ở ranh giới frontend/backend, và không cần bàn giao qua nhiều người.',
      items: [
        { num: '01', title: 'Tốc độ', body: 'Tính năng cần được giao trọn vẹn bởi một người hiểu cả API lẫn UI — giảm thời gian chờ và chi phí phối hợp.' },
        { num: '02', title: 'Chất lượng', body: 'Code cần sạch và dễ bảo trì để sản phẩm mở rộng được — không chỉ chạy được hôm nay.' },
        { num: '03', title: 'Trách nhiệm', body: 'Bug từ khách hàng cần một người nhận trách nhiệm từ chẩn đoán đến bản vá, không đùn đẩy giữa các team.' },
      ],
    },
    s3: {
      num: '04',
      cmd: '$ cat solution.md',
      title: 'Giải pháp đề xuất',
      intro: 'Một fullstack developer đã quen làm việc trong sản phẩm thương mại thực tế, đảm nhận trọn vẹn ba lớp công việc:',
      items: [
        { tag: '// backend', title: 'API & Logic', body: 'Thiết kế và triển khai API với NestJS/NodeJS, mô hình dữ liệu MongoDB/SQL, tích hợp bên thứ ba (thanh toán, OTP, CRM).' },
        { tag: '// frontend', title: 'React & Next.js', body: 'Xây UI production với React/Next.js — từ dashboard quản trị (Polaris) đến storefront hiệu năng cao cho người dùng cuối.' },
        { tag: '// ownership', title: 'End-to-end', body: 'Nhận một yêu cầu và đưa đến production: thiết kế, code, test, deploy, và xử lý bug sau khi phát hành.' },
      ],
    },
    s4: {
      num: '05',
      cmd: '$ ls -la ./scope',
      title: 'Phạm vi công việc có thể đảm nhận',
      rows: [
        { label: 'API & backend', body: 'Thiết kế REST/GraphQL API, xác thực đa lớp (OAuth, OTP, token), aggregation pipelines cho analytics.' },
        { label: 'Admin CMS', body: 'Dashboard quản trị với live preview, phân quyền theo vai trò, import/export hàng loạt, đa ngôn ngữ.' },
        { label: 'Storefront / UI', body: 'UI người dùng cuối hiệu năng cao — variant picker, swatch, gallery — trên Shopify Storefront API hoặc web app thuần.' },
        { label: 'Realtime', body: 'Thông báo và chat thời gian thực với Socket.io, Server-Sent Events, Firebase Firestore.' },
        { label: 'Tích hợp', body: 'Thanh toán (VNPay), OTP (Twilio), AI (Gemini — chatbot, kiểm duyệt nội dung), e-contract render PDF.' },
        { label: 'Vận hành', body: 'Deploy production trên Docker + Linux, xử lý bug từ người dùng thực từ chẩn đoán đến bản vá.' },
      ],
    },
    s5: {
      num: '06',
      cmd: '$ git log --reverse --since="day 0" --until="day 90"',
      title: 'Lộ trình 90 ngày đầu',
      items: [
        { range: 'Ngày 0 → 30', title: 'Hoà nhập & đóng góp đầu tiên', body: 'Nắm codebase, quy trình và domain sản phẩm. Nhận bug fix và tính năng nhỏ để ship code lên production ngay trong tháng đầu.' },
        { range: 'Ngày 30 → 60', title: 'Đảm nhận tính năng độc lập', body: 'Nhận tính năng vừa và lớn từ yêu cầu đến release — thiết kế kỹ thuật, triển khai cả backend lẫn frontend, tự test và bàn giao.' },
        { range: 'Ngày 60 → 90', title: 'Làm chủ một module', body: 'Chịu trách nhiệm chính một module/mảng sản phẩm: roadmap kỹ thuật, chất lượng code, và hỗ trợ thành viên khác trong mảng đó.' },
      ],
    },
    s6: {
      num: '02',
      cmd: '$ ls -la ./case-studies',
      title: 'Dự án tiêu biểu',
      shopify: {
        title: 'Shopify Apps — BSS Commerce',
        year: '2026',
        role: 'App Developer · NestJS + Remix/Polaris + Lit',
        highlights: [
          {
            label: 'Phát triển app',
            body: 'Xây dựng tính năng cho hai app "Built for Shopify" đang chạy trên App Store — từ giao diện khách mua hàng nhìn thấy khi chọn biến thể/tuỳ chọn sản phẩm, đến trang quản trị merchant dùng để cấu hình, xem trước thay đổi ngay lập tức, và import/export dữ liệu số lượng lớn.',
          },
          {
            label: 'Chăm sóc khách hàng',
            body: 'Trực tiếp xử lý các trường hợp merchant báo lỗi khi dùng app trên store thật của họ — tái hiện lỗi trong đúng cấu hình/theme của từng merchant, xác định nguyên nhân, sửa code, và theo đến khi merchant xác nhận đã dùng được bình thường.',
          },
        ],
      },
      projects: [
        {
          name: 'RetroTrade', period: '09/2025 – 12/2025', role: 'Fullstack Developer & Leader · nhóm 5 người',
          body: 'Nền tảng cho thuê đồ dùng — chia sẻ, thuê và tái sử dụng. Xác minh danh tính bằng OCR CMND + face-matching, luồng thuê end-to-end, hợp đồng điện tử ký AES render PDF, kiểm duyệt nội dung bằng AI.',
          stack: ['Next.js', 'TypeScript', 'NodeJS', 'MongoDB', 'Socket.io', 'Twilio'],
        },
        {
          name: 'Nutigo', period: '01/2025 – 03/2025', role: 'Fullstack Developer & Leader · nhóm 4 người',
          body: 'Nền tảng phân phối thực phẩm lành mạnh hỗ trợ đặt hàng sỉ. Luồng mua hàng MERN đầy đủ với VNPay, engine giảm giá tự hết hạn theo cron, chatbot AI (Gemini), deploy production trên Docker + Linux.',
          stack: ['React', 'TypeScript', 'NodeJS', 'MongoDB', 'Firebase', 'Docker'],
        },
      ],
    },
    s7: {
      num: '07',
      cmd: '$ cat next-steps.md',
      title: 'Điều khoản làm việc & bước tiếp theo',
      termsCmd: '$ cat terms.md',
      terms: {
        type: 'hình thức', typeValue: 'Full-time',
        start: 'bắt đầu', startValue: 'Ngay khi thống nhất',
        location: 'địa điểm', locationValue: 'Hà Nội / Remote',
        probation: 'thử việc', probationValue: 'Theo chính sách công ty',
      },
      contactCmd: '$ cat contact.md',
      steps: [
        { label: 'step 1', title: 'Xem hồ sơ', body: 'Xem CV đính kèm và các dự án live được liên kết trong tài liệu này.' },
        { label: 'step 2', title: 'Trao đổi', body: 'Một buổi trao đổi ngắn qua điện thoại hoặc phỏng vấn trực tiếp/online.' },
        { label: 'step 3', title: 'Bài test kỹ thuật', body: 'Sẵn sàng làm bài test kỹ thuật hoặc thử việc theo quy trình của công ty.' },
      ],
      ctaEmail: 'gửi email →',
      ctaCv: '↓ tải cv.pdf',
    },
    footer: '© 2026 Lưu Minh Đức · $ exit 0',
  },
  en: {
    nav: { home: 'duc@proposal:~' },
    hero: {
      cmd: '$ cat proposal.md',
      title1: 'Proposal for Collaboration',
      title2: 'Fullstack Developer',
      subtitle:
        'Capabilities, scope of work, and a 90-day contribution plan — everything your team needs before we talk. About a 4-minute read.',
      fields: {
        name: 'name',
        nameValue: 'Luu Minh Duc',
        role: 'role',
        roleValue: 'Fullstack Developer',
        experience: 'experience',
        experienceValue: 'BSS Commerce · FPT Software',
        to: 'prepared for',
        toDefault: 'Hiring Team',
      },
      ctaContact: 'get in touch →',
      ctaCv: '↓ cv.pdf',
    },
    s1: {
      num: '01',
      cmd: '$ whoami --verbose',
      title: 'Introduction & Capabilities',
      name: 'Luu Minh Duc',
      tagline: 'Fullstack Developer · MERN & Next.js · FPT University (SE, 2021–2025)',
      bio1: 'I build products end to end — from database design and API work down to the pixels a user actually touches. My background spans Shopify app development at BSS Commerce, an Intern → Fresher React track at FPT Software, and leading two full-stack projects from zero to production.',
      bio2: 'I care about clean, maintainable code and pick up new technology fast — I take end-to-end ownership rather than just one slice of the system.',
      traits: ['Problem solver', 'Fast learner', 'Team lead experience', 'Ships end to end'],
      skillGroups: [
        { key: 'languages', tags: ['JavaScript', 'TypeScript', 'Java'] },
        { key: 'frameworks', tags: ['React', 'Next.js', 'NestJS', 'Redux Toolkit', 'TanStack Query'] },
        { key: 'database', tags: ['MongoDB', 'MySQL', 'SQL Server', 'PostgreSQL', 'GraphQL'] },
        { key: 'other', tags: ['Socket.io', 'Firebase', 'Docker', 'Shopify APIs'] },
      ],
    },
    s2: {
      num: '03',
      cmd: '$ cat context.md',
      title: 'Context & Need',
      intro: 'An effective product team needs a developer who can take a requirement all the way to production — not stop at the frontend/backend boundary, and not require a handoff through several people.',
      items: [
        { num: '01', title: 'Speed', body: 'Features shipped end to end by one person who understands both the API and the UI — less waiting, less coordination overhead.' },
        { num: '02', title: 'Quality', body: 'Code that stays clean and maintainable as the product grows — not just code that works today.' },
        { num: '03', title: 'Ownership', body: 'Customer-reported bugs handled by one person from diagnosis to fix, with no bouncing between teams.' },
      ],
    },
    s3: {
      num: '04',
      cmd: '$ cat solution.md',
      title: 'Proposed Solution',
      intro: 'A fullstack developer already comfortable in real commercial products, covering three layers of work end to end:',
      items: [
        { tag: '// backend', title: 'API & Logic', body: 'Designing and shipping APIs with NestJS/NodeJS, MongoDB/SQL data models, and third-party integrations (payments, OTP, CRM).' },
        { tag: '// frontend', title: 'React & Next.js', body: 'Building production UI with React/Next.js — from admin dashboards (Polaris) to high-performance storefronts for end users.' },
        { tag: '// ownership', title: 'End to end', body: 'Taking a requirement to production: design, code, test, deploy, and handling bugs after release.' },
      ],
    },
    s4: {
      num: '05',
      cmd: '$ ls -la ./scope',
      title: 'Scope of Work I Can Own',
      rows: [
        { label: 'API & backend', body: 'REST/GraphQL API design, multi-layer auth (OAuth, OTP, token), aggregation pipelines for analytics.' },
        { label: 'Admin CMS', body: 'Admin dashboards with live preview, role-based permissions, bulk import/export, multi-language support.' },
        { label: 'Storefront / UI', body: 'High-performance end-user UI — variant pickers, swatches, galleries — on the Shopify Storefront API or plain web apps.' },
        { label: 'Realtime', body: 'Real-time notifications and chat with Socket.io, Server-Sent Events, Firebase Firestore.' },
        { label: 'Integrations', body: 'Payments (VNPay), OTP (Twilio), AI (Gemini — chatbot, content moderation), e-contract PDF rendering.' },
        { label: 'Operations', body: 'Production deploys on Docker + Linux, handling real-user bugs from diagnosis to fix.' },
      ],
    },
    s5: {
      num: '06',
      cmd: '$ git log --reverse --since="day 0" --until="day 90"',
      title: 'First 90 Days',
      items: [
        { range: 'Day 0 → 30', title: 'Ramp up & first contributions', body: 'Learn the codebase, process, and product domain. Ship bug fixes and small features to production within the first month.' },
        { range: 'Day 30 → 60', title: 'Own features independently', body: 'Take medium and large features from requirement to release — technical design, backend and frontend implementation, self-testing, and handoff.' },
        { range: 'Day 60 → 90', title: 'Own a module', body: 'Take lead responsibility for one product module: technical roadmap, code quality, and supporting other team members in that area.' },
      ],
    },
    s6: {
      num: '02',
      cmd: '$ ls -la ./case-studies',
      title: 'Featured Work',
      shopify: {
        title: 'Shopify Apps — BSS Commerce',
        year: '2026',
        role: 'App Developer · NestJS + Remix/Polaris + Lit',
        highlights: [
          {
            label: 'Building the app',
            body: 'Built features for two "Built for Shopify" apps live on the App Store — from what shoppers see when picking product variants/options, to the admin dashboard merchants use to configure it, preview changes instantly, and bulk import/export data.',
          },
          {
            label: 'Customer support',
            body: "Handled merchant-reported issues directly on their live stores — reproducing the bug in their exact theme/setup, finding the root cause, shipping a fix, and following up until the merchant confirmed it was resolved.",
          },
        ],
      },
      projects: [
        {
          name: 'RetroTrade', period: '09/2025 – 12/2025', role: 'Fullstack Developer & Leader · team of 5',
          body: 'A rental platform for sharing, renting, and reusing items. Identity verification via OCR ID extraction + face matching, an end-to-end rental flow, AES-signed e-contracts rendered to PDF, and AI content moderation.',
          stack: ['Next.js', 'TypeScript', 'NodeJS', 'MongoDB', 'Socket.io', 'Twilio'],
        },
        {
          name: 'Nutigo', period: '01/2025 – 03/2025', role: 'Fullstack Developer & Leader · team of 4',
          body: 'A healthy-food distribution platform supporting wholesale ordering. Full MERN shopping flow with VNPay, a self-expiring cron-based discount engine, an AI chatbot (Gemini), and production deploys on Docker + Linux.',
          stack: ['React', 'TypeScript', 'NodeJS', 'MongoDB', 'Firebase', 'Docker'],
        },
      ],
    },
    s7: {
      num: '07',
      cmd: '$ cat next-steps.md',
      title: 'Working Terms & Next Steps',
      termsCmd: '$ cat terms.md',
      terms: {
        type: 'type', typeValue: 'Full-time',
        start: 'start', startValue: 'As soon as agreed',
        location: 'location', locationValue: 'Hanoi / Remote',
        probation: 'probation', probationValue: 'Per company policy',
      },
      contactCmd: '$ cat contact.md',
      steps: [
        { label: 'step 1', title: 'Review my profile', body: "Check the attached CV and the live projects linked throughout this document." },
        { label: 'step 2', title: 'Talk', body: 'A short call or an in-person/online interview.' },
        { label: 'step 3', title: 'Technical assessment', body: "Happy to complete a technical test or trial period per your process." },
      ],
      ctaEmail: 'send an email →',
      ctaCv: '↓ download cv.pdf',
    },
    footer: '© 2026 Luu Minh Duc · $ exit 0',
  },
} as const
